src/mapping3/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

from dashboard import views as DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',include('newsapp.urls')),
    

    path('', DashboardView.index, name='index'),
    #path('',DashboardView.topfive, name= 'index'),

    #path('about-us', news_views.aboutUs, name='aboutUs'),

    

    #path('', news_views.news, name='index'),
    # path('news',news_views.news, name= 'news'),
    # path('all-news',news_views.all_news, name= 'all-news'),
    # #path('detail/<int:id>',news_views.detail,name='detail'),
    # path('all-category',news_views.all_category, name='all-category'),
    # path('Fungicides', news_views.Fungicides, name='Fungicides'),
    # path('Herbicides', news_views.Herbicides, name='Herbicides'),
    # path('Insecticides', news_views.Insecticides, name='Insecticides'),
    # path('Mothballs', news_views.Mothballs, name='Mothballs'),
    # path('category/<int:id>',news_views.category,name='category'),
    # path('Crop', news_views.Crop, name='Crop'),
    # path('contact-us', news_views.contactUs, name='contactUs'),
    #path('Getnews', include('newsapp.urls')),
    #path('news', include('newsapp.urls'))
    

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

src/newsapp/urls.py

from tokenize import Name
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from dashboard import views as dashboard_view

from . import views


 
urlpatterns = [
    path('all-news',views.all_news,name='all-news'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('all-category',views.all_category,name='all-category'),
    path('category/<int:id>',views.category,name='category'),

    path('news', views.news, name='news'),
    
    path('Fungicides', views.Fungicides, name='Fungicides'),
    path('Herbicides', views.Herbicides, name='Herbicides'),
    path('Insecticides', views.Insecticides, name='Insecticides'),
    path('Mothballs', views.Mothballs, name='Mothballs'),
    path('Crop', views.Crop, name='Crop'),
    
    
    path('about-us',views.aboutUs,name='aboutUs'),
    path('contact-us',dashboard_view.contact,name='contact-us'),

    #path('', dashboard_view.index, name='index'),
    
    
    




    ]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/newsapp/models.py
from tabnanny import verbose
from django.db import models
from matplotlib.pyplot import title
from django.utils.translation import gettext as _

# class showAI(models.Model):
#     #id= models.ForeignKey()
#     state_no = models.FloatField(_("state_no"), max_length=255)
#     crop_name= models.CharField(_("crop_name"), max_length=255)
#     yieldd= models.FloatField(_("yield"), max_length=255)
#     # def __str__(self):
#     #     return self.state_no,self.yieldd,self.crop_name
#     class Meta:
#         verbose_name_plural='ShowAI'



class Category(models.Model):
    title=models.CharField(max_length=200)
    category_image=models.ImageField(upload_to='imgs/')

    class Meta:
        verbose_name_plural='Categories'

    def __str__(self):
        return self.title

#news model creating here

class News(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    image=models.ImageField(upload_to='imgs/')
    detail=models.TextField()
    add_time=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='News'

    def __str__(self):
        return self.title

#cmt model
class Comment(models.Model):
    news=models.ForeignKey(News,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=200)
    comment=models.TextField()
    status=models.BooleanField(default=True)
    

    class Meta:
        verbose_name_plural='Comments'

    def __str__(self):
        return self.comment



src/templates/Fungicides.html
{% extends 'base.html' %}
{% block content %}



<!DOCTYPE html>
<html lang="en">
    <title>{% block title %}Pesticides{% endblock %}</title>
    <body> 
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">Fungicides</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on April 12, 2022 by vinay</div>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="/media/Fungicides.jpg" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">Fungicides are pesticides that kill or prevent the growth of fungi and their spores. They can be used to control fungi that damage plants, including rusts, mildews and blights. They might also be used to control mold and mildew in other settings. Fungicides work in a variety of ways, but most of them damage fungal cell membranes or interfere with energy production within fungal cells.</p>
                            <p class="fs-5 mb-4">A fungal disease in plants can be misdiagnosed easily. Check with your local county extension office for help identifying plant disease. They may also be able to recommend a treatment strategy for your lawn or garden.
                                Often, plant diseases are transmitted when leaves are wet. Ground level watering and good air circulation can be used to keep leaves dry.</p>
                            <p class="fs-5 mb-4">Many fungicides remain on the surface of plant tissues and do not spread throughout the plant. Others penetrate the cuticle and circulate through plant tissues.</p>
                            <h2 class="fw-bolder mb-4 mt-5">Keep these tips in mind when using fungicides:</h2>
                            <p class="fs-5 mb-4">Pruning shears and other tools can carry plant diseases from one plant to another. Learn about garden sanitation to prevent spreading fungal pathogens yourself.</p>
                            <p class="fs-5 mb-4">Many fungicides remain on the surface of plant tissues and do not spread throughout the plant. Others penetrate the cuticle and circulate through plant tissues.</p>
                        </section>
                    </article>
<!-- Comments section-->
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            
        </div>
    </div>
</section>
</div>

<div class="col-lg-4">

<div class="card mb-4">
 
<div class="card mb-4">
    <!-- Side widgets-->
    <div class="card-header">Why are Fungicides Needed?</div>
    <div class="card-body"> Diseases are a common occurrence on plants, often having a significant economic impact on yield and quality, thus managing diseases is an essential component of production for most crops. Broadly, there are three main reasons fungicides are used: (a) To control a disease during the establishment and development of a crop. (b) To increase productivity of a crop and to reduce blemishes. Diseased food crops may produce less because their leaves, which are needed for photosynthesis, are affected by the disease (Figures 8 - 11). Blemishes can affect the edible part of the crop (Figures 6 and 14) or, in the case of ornamentals, their attractiveness (Figures 12 - 13), which both can affect the market value of the crop. (c) To improve the storage life and quality of harvested plants and produce. Some of the greatest disease losses occur post-harvest (Figures 14 and 15). Fungi often spoil (render unusable) stored fruits, vegetables, tubers, and seeds. A few which infect grains produce toxins (mycotoxins) capable of causing severe illness or even death in humans and animals when consumed. Fungicides have been used to reduce mycotoxin contamination in wheat affected by Fusarium head blight, but most fungicides developed so far have not been sufficiently effective to be useful for managing mycotoxins associated with other diseases.</div>
</div>
    
</div>


</div>
</div>
</div>



{% endblock %}

src/templates/Herbicides.html
{% extends 'base.html' %}
{% block content %}



<!DOCTYPE html>
<html lang="en">
    <title>{% block title %}Pesticides{% endblock %}</title>
    <body> 
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">herbicide</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on April 12, 2022 by Mohan</div>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="/media/Herbicides.jpg" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">herbicide, an agent, usually chemical, for killing or inhibiting the growth of unwanted plants, such as residential or agricultural weeds and invasive species. A great advantage of chemical herbicides over mechanical weed control is the ease of application, which often saves on the cost of labour. Most herbicides are considered nontoxic to animals and humans, but they can cause substantial mortality of nontarget plants and the insects that depend on them, especially when applied aerially.</p>
                            <p class="fs-5 mb-4">Chemical weed control has been used for a very long time: sea salt, industrial by-products, and oils were first employed. Selective control of broad-leaved weeds in fields of cereal crops was discovered in France in the late 1800s, and this practice soon spread throughout Europe. Sulfates and nitrates of copper and iron were used, and sulfuric acid proved even more effective. Application was by spraying. Soon sodium arsenite became popular both as a spray and as a soil sterilant. On thousands of kilometres of railroad right-of-way, and in sugarcane and rubber plantations in the tropics, the hazardous material was used in tremendous quantities, often resulting in the poisoning of animals and occasionally humans.</p>
                            <p class="fs-5 mb-4">Sinox, the first major organic chemical herbicide, was developed in France in 1896. In the late 1940s new herbicides were developed out of the research during World War II, and the era of the “miracle” weed killers began. Within 20 years over 100 new chemicals were synthesized, developed, and put into use. Chemical weed control superseded both plant-disease and insect-pest control in economic impact. In particular, the year 1945 was key to the development of selective chemical weed control. Introduced then were 2,4-D (2,4-dichlorophenoxyacetic acid), 2,4,5-T (2,4,5-trichlorophenoxyacetic acid), and IPC (isopropyl-N-phenylcarbamate)—the first two selective as foliar sprays against broad-leaved weeds, the third selective against grass species when applied through the soil.</p>
                            <h2 class="fw-bolder mb-4 mt-5">The new herbicides were revolutionary in that their high toxicity allowed for effective weed control at dosage rates as low as one to two kilograms per hectare
                                 (one or two pounds per acre).</h2>
                            <p class="fs-5 mb-4"> This contrasted with carbon bisulfide, borax, and arsenic trioxide,
                                which were required at rates of up to 2,242 kilograms per hectare (one ton per acre), and with sodium chlorate, 
                                required at rates of around 112 kilograms per hectare (100 pounds per acre). However, some of those early herbicides,
                                 including 2,4,5-T, were later deemed unsafe for humans and the environment and were discontinued in many countries. 
                                 Effective herbicides have continued to be developed, and some, such as glyphosate, are widely used around the world. Herbicides are used in agricultural and wildland ecosystems to reduce the density of weeds and promote the growth of desirable species. Use of herbicides in agroecosystems may change composition of weed populations. In wildlands, herbicides may increase the diversity of native species. Threats to plant biodiversity caused by habitat loss and invasive species are far greater than threats by use of herbicides. This article reviews concepts of weeds; principles of weed management; and categories, action, and fate of herbicides. Impacts of herbicides on biodiversity of target and nontarget species and the role of weed control in preserving biodiversity are also discussed.</p>
                            <p class="fs-5 mb-4">There are many groups of herbicides with different chemistries and different toxic mechanisms of action. The principal toxic mechanisms that affect plants are sometimes the same as those that affect animals. In other instances, a unique aspect of plant biochemistry may be targeted by a herbicide, but a different type of biochemical receptor may be important in exposed animals.</p>
                        </section>
                    </article>
<!-- Comments section-->
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            
        </div>
    </div>
</section>
</div>

<div class="col-lg-4">

<div class="card mb-4">
 
<div class="card mb-4">
    <!-- Side widgets-->
    <div class="card-header">Application</div>
    <div class="card-body">Modern weed killers are put in two categories: selective (affecting specific plant species) and nonselective (affecting plants generally). These, in turn, are classified as foliage-applied and soil herbicides. Contact herbicides (e.g., sulfuric acid, diquat, paraquat) kill only the plant organs with which they are in contact. Translocated herbicides (e.g., amitrole, picloram, and 2,4-D) are effective against roots or other organs to which they are transported from aboveground treated surfaces (i.e., soil). With respect to planting time, herbicides are also classified as preplant, preemergence, or postemergence weed killers. Preplant herbicides may be applied to the soil or to weeds before crop planting.</div>
</div>
    
</div>


</div>
</div>
</div>



{% endblock %}

src/templates/Insecticides.html
{% extends 'base.html' %}
{% block content %}



<!DOCTYPE html>
<html lang="en">
    <title>{% block title %}Pesticides{% endblock %}</title>
    <body> 
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">Insecticides</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on April 12, 2022 by Vinay</div>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="/media/Insecticides.jpg" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">Insecticides are pesticides that are formulated to kill, harm, repel or mitigate one or more species of insect. Insecticides work in different ways. Some insecticides disrupt the nervous system, whereas others may damage their exoskeletons, repel them or control them by some other means. They can also be packaged in various forms including sprays, dusts, gels, and baits. Because of these factors, each insecticide can pose a different level of risk to non-target insects, people, pets and the environment.</p>
                            <p class="fs-5 mb-4">insecticide, any toxic substance that is used to kill insects. Such substances are used primarily to control pests that infest cultivated plants or to eliminate disease-carrying insects in specific areas.</p>
                            <p class="fs-5 mb-4">Most synthetic insecticides penetrate by all three of these pathways, however, and hence are better distinguished from each other by their basic chemistry. Besides the synthetics, some organic compounds occurring naturally in plants are useful insecticides, as are some inorganic compounds; some of these are permitted in organic farming applications. Most insecticides are sprayed or dusted onto plants and other surfaces traversed or fed upon by insects.

                                Modes of penetration Insecticides can be classified in any of several ways, on the basis of their chemistry, their toxicological action, or their mode of penetration. In the latter scheme, they are classified according to whether they take effect upon ingestion (stomach poisons), inhalation (fumigants), or upon penetration of the body covering (contact poisons). </p>
                            <h2 class="fw-bolder mb-4 mt-5">Modes of penetration</h2>
                            <p class="fs-5 mb-4">Stomach poisons are toxic only if ingested through the mouth and are most useful against those insects that have biting or chewing mouth parts, such as caterpillars, beetles, and grasshoppers. The chief stomach poisons are the arsenicals—e.g., Paris green (copper acetoarsenite), lead arsenate, and calcium arsenate; and the fluorine compounds, among them sodium fluoride and cryolite. They are applied as sprays or dusts onto the leaves and stems of plants eaten by the target insects. Stomach poisons have gradually been replaced by synthetic insecticides, which are less dangerous to humans and other mammals.</p>
                            <p class="fs-5 mb-4">Contact poisons penetrate the skin of the pest and are used against those arthropods, such as aphids, that pierce the surface of a plant and suck out the juices. The contact insecticides can be divided into two main groups: naturally occurring compounds and synthetic organic ones. The naturally occurring contact insecticides include nicotine, developed from tobacco; pyrethrum, obtained from flowers of Chrysanthemum cinerariaefolium and Tanacetum coccineum; rotenone, from the roots of Derris species and related plants; and oils, from petroleum. Though these compounds were originally derived mainly from plant extracts, the toxic agents of some of them (e.g., pyrethrins) have been synthesized. Natural insecticides are usually short-lived on plants and cannot provide protection against prolonged invasions. Except for pyrethrum, they have largely been replaced by newer synthetic organic insecticides.</p>
                        </section>
                    </article>
<!-- Comments section-->
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            
        </div>
    </div>
</section>
</div>

<div class="col-lg-4">

<div class="card mb-4">
 
<div class="card mb-4">
    <!-- Side widgets-->
    <div class="card-header">Keep these tips in mind:</div>
    <div class="card-body">Practicing Integrated Pest Management can significantly reduce the amount of insecticides needed to control many insect problems.
        Using more than one insecticide product in the same location can increase or decrease each one's effectiveness. It may also result in a greater risk to health and/or the environment.
        Broad-spectrum insecticides are effective against all insects, even the good ones. Other insecticides target certain insects. Using a targeted insecticide minimizes the risk to beneficial or non-target insects.
        Some insecticides work immediately to kill insects while others may need some time to take effect.
        Insect growth regulators like pyriproxyfen and methoprene do not kill insects; they make it impossible for exposed insects to molt (grow) or lay eggs properly.
        Insecticidal baits can be used instead of spraying large areas, especially for social insects like ants. This can decrease the risk of exposure, but remember to place baits where children and pets won't have access.</div>
</div>
    
</div>


</div>
</div>
</div>



{% endblock %}

src/templates/Mothballs.html
{% extends 'base.html' %}
{% block content %}



<!DOCTYPE html>
<html lang="en">
    <title>{% block title %}Pesticides{% endblock %}</title>
    <body> 
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">Mothballs</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on April 12, 2022 by Mohan</div>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="/media/Mothballs.jpg" alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">Mothballs are classified as a pesticide and used to
                                control moths, silverfish and other fiber pests in
                                wool and other natural fiber clothing and materials.
                                Mothballs should only be used as specified on
                                the label, and their use is regulated by the U.S.
                                Environmental Protection Agency (EPA). </p>
                            <p class="fs-5 mb-4">Mothballs are commonly made of naphthalene or paradichlorobenzene, both of which are toxic to humans.
                                These chemicals are solids at room temperature and
                                are made into round balls, flakes or cakes that slowly
                                change to a gas and become fumes in the air.</p>
                            <p class="fs-5 mb-4">The chemicals in mothballs are toxic to humans and
                                pets. People are exposed to the chemicals in mothballs
                                by inhaling the fumes. If you smell mothballs, you are
                                being exposed to these chemicals. Children or pets
                                sometimes mistake mothballs for food or candy and
                                eat them, which can cause serious effects.
                                Some of the chemicals in mothballs can cause
                                reversible health effects that include headaches,
                                nausea, eye and nose irritation and coughing.
                                Exposure to naphthalene can cause more serious
                                effects, including hemolytic anemia. Naphthalene
                                is also a possible carcinogen. Extended exposure to
                                mothballs can also cause liver and kidney damage.
                                </p>
                            <h2 class="fw-bolder mb-4 mt-5">Mothballs should never be used in
                                schools, daycare centers and
                                other public buildings. </h2>
                            <p class="fs-5 mb-4">an effective, multipronged and safe way to monitor,
                                identify, prevent and control pests. IPM includes the
                                following steps:
                                 identify the specific pest in order to target
                                preventive and control actions;
                                 monitor to assess pest numbers, damage and
                                locations;
                                 implement preventive measures, such as removing
                                food sources, making habitat undesirable (e.g.,
                                remove tall grass) and putting up physical barriers;
                                and
                                 control pests through selective measures, such as
                                trapping and removing pests or using pesticides
                                specific for the pest in an appropriate and
                                minimal fashion.
                                If pesticides are used, be sure to follow the label
                                instructions exactly in order to use them safely
                                and correctly.</p>
                            <p class="fs-5 mb-4">Mothballs should not be placed in closets, attics,
                                basements, storage chests or trunks, garment bags or
                                other spaces other than in tightly closed containers as
                                explained above. Gasses from the mothballs escape
                                into the air and can cause respiratory problems.
                                High levels of the chemical fumes can accumulate in
                                closed areas. Improper use of mothballs can lead to
                                long term exposures to people and pets. The fumes
                                are heavier than air and will accumulate along floors,
                                posing a danger to small children and pets.</p>
                        </section>
                    </article>
<!-- Comments section-->
<section class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            
        </div>
    </div>
</section>
</div>

<div class="col-lg-4">

<div class="card mb-4">
 
<div class="card mb-4">
    <!-- Side widgets-->
    <div class="card-header">Common Illegal Pesticide Products</div>
    <div class="card-body">Illegal naphthalene moth repellent products -- mothballs -- are hazardous to young children. Mothballs can easily be mistaken for candy, or simply tempt young children to touch and play with them. Recent studies link naphthalene to illnesses, including nasal cancer. Widespread sale of illegal mothball products is a particular concern.
        Illegal pet products, including foreign versions of the well-known EPA-registered pet products Advantage and Frontline, have been illegally imported and sold throughout the United States. Though registered for use in other countries, some foreign-labeled versions omit important warnings pertaining to children or give doses in metric units, which can cause Americans to accidentally over-dose or under-dose pets.</div>
</div>
    
</div>


</div>
</div>
</div>



{% endblock %}

src/templates/all-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">All News</h3>
    <!-- News Box -->  
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

src/templates/news.html
{% extends 'base.html' %}
{% block content %}
<!-- 14:25 / 43:04 -->
<title>{% block title %}News{% endblock %}</title>
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-7">
			<div class="card mb-3">
			  <img src="media/{{first_news.image}}" class="card-img-top" alt="{{first_news.title}}">
			  <div class="card-body">
				  
				  
			    <h5 class="card-title">{{first_news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			  </div>
			</div>
		</div>
		<!-- Right -->
		<div class="col-md-5" style="max-height: 450px; overflow: auto;">
			{% for news in three_news %}
			<!-- News Box -->
			<div class="card">
			  <div class="row no-gutters">
			    <div class="col-md-4">
					<img src="media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			    </div>
			    <div class="col-md-8">
			      <div class="card-body">
			        <h5 class="card-title">{{news.title}}</h5>
			        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			      </div>
			    </div>
			  </div>
			</div>
			<hr/>
			{% endfor %}
		</div>
	</div>
	<!-- Category Wise News -->
	{% for category in three_categories %}
	<h3 class="border-bottom pb-1">{{category.title}} <a href="/category/{{category.id}}" class="float-right btn btn-sm btn-dark">In this Category</a></h3>
	<div class="row my-4">
		{% for news in category.news_set.all %}
		    {% if forloop.counter < 5 %}
			<!-- News box -->
			<div class="col-md-3">
				<div class="card mb-3 shadow">
				<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr/>
					<p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
				</div>
				</div>
			</div>
            {% endif %}
		{% endfor %}
	</div>
	{% endfor %}
	
	<!-- End Single Category -->
</main>
{% endblock %}